- name: "update"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python-pip
    - python3-pip
- name: "Install python docker module"
  pip:
    name:
    - docker
    - jsondiff
- name: "get keys"
  apt_key:
          url: https://download.docker.com/linux/debian/gpg
          state: present
- name: "make repo"
  apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present
- name: "Install Docker Engine"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: "add user to docker group"
  user:
        name: "{{ ansible_user }}"
        group: docker
        state: present

