- name: 'Install dependencies'
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true
- name: 'Starting Nginx'
  service:
    name: nginx
    state: started
- name: 'Install Template'
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: 'Restart Nginx'
  service:
    name: nginx
    state: reloaded