- name: "Join a swarm"
  docker_swarm:
          state: join
          remote_addrs: [ "{{ hostvars['manager']['ansible_default_ipv4']['address'] }}:2377" ]
          advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          join_token: "{{ hostvars['token']['value'] }}"
